apiVersion: v2
name: judge0
version: 1.13.0
appVersion: 1.0
description: Iamneo.ai | Helm implementation of Judge0 | Free,robust and scalable open-source online code execution system.
keywords:
  - examly-compiler
  - competitive-programming
  - code-executor
  - code-runner
  - code-execution
  - judge0
  - compiler
home: https://api.judge0.com
icon: https://github.com/judge0/api/raw/master/.github/wallpaper.png?raw=true
sources:
  - https://github.com/judge0/judge0
dependencies:
  - name: postgresql
    version: 13.0.0
    repository: https://docker.io/bitnami/postgresql
    condition: postgresql.enabled
    tags:
      - 13.0.0
  - name: redis
    version: 6.0
    repository: https://docker.io/bitnami/redis
    condition: redis.enabled
    tags:
      - 6.0
maintainers:
  - name: iamneo.ai
    email: techadmin@iamneo.ai
    url: https://gitlab.com/iamneo.ai
